services:
  - type: web
    name: gdprcheck360-api
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true